## IMPORT LIBRARY 📚

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import distance

## Hitung Jarak Titik Euclidean 📏

In [ ]:
def euclidean(x, p):
  return distance.euclidean(x, p)

## K-Means Algorithm For K Cluster ⚡

In [ ]:
def kmeans(cluster, x, y, px, py, itr):
  n = len(x)
  d = np.zeros([cluster, n])
  g = np.zeros([cluster, n])
  nsum = np.zeros(cluster)
  xsum = np.zeros(cluster)
  ysum = np.zeros(cluster)
  compareMin = np.zeros(cluster)
  pxnew = np.zeros(cluster)
  pynew = np.zeros(cluster)

  for i in range(0, n):
    # Mencari jarak titik dengan centroid
    xy = np.array([x[i], y[i]])
    for j in range(0, cluster):
      cent = np.array([px[j], py[j]])
      d[j][i] = euclidean(xy, cent)
      compareMin[j] = d[j][i]
    # Clustering berdasarkan nilai paling dekat dengan 0
    idxMin = 0
    minValue = compareMin[0]
    for k in range(0, cluster):
      if ( minValue > compareMin[k] ):
        idxMin = k
        minValue = compareMin[k]
    g[idxMin][i] = 1

  # Membuat nilai centroid baru
  for i in range(0, cluster):
    for j in range(0, n):
      if (g[i][j] == 1):
        nsum[i] = nsum[i] + 1
        xsum[i] = xsum[i] + x[j]
        ysum[i] = ysum[i] + y[j]
  for i in range(0, cluster):
    xmean = xsum[i]/nsum[i]
    ymean = ysum[i]/nsum[i]
    pxnew[i] = xmean
    pynew[i] = ymean

  # Print Detail Komputasi
  print("iterasi ke-", itr)
  print('x = ', x)
  print('y = ', y)
  for i in range(0, cluster):
    cent = np.array([px[i], py[i]])
    print("P ke-", i+1, ': ', cent)
  print("\n")
  
  print("Hasil distance: ")
  print(d)
  print("\n")

  print("Hasil clustering: ")
  print(g)
  print("\n")

  for i in range(0, cluster):
    print("nsum cluster ke-", i, ': ', nsum[i])
    print("xsum cluster ke-", i, ': ', xsum[i])
    print("ysum cluster ke-", i, ': ', ysum[i])
    print('\n')

  print('pnew:')
  for i in range(0, cluster):
    cent = np.array([pxnew[i], pynew[i]])
    print("P new ke-", i+1, ': ', cent)
  print("\n==============================================================\n")

  # Cek centroid awal dan centroid baru apakah sama
  loop = 0
  valid = True
  while(valid and loop < cluster):
    if((px[loop] != pxnew[loop]) or (py[loop] != pynew[loop])):
      valid = False
    loop = loop + 1
  
  # Jika nilai centroid baru dan lama berbeda maka lakukan rekursif
  if(valid == False):
    itr = itr + 1
    kmeans(cluster, x, y, pxnew, pynew, itr)



## Contoh Kasus 2 Cluster (Jangan Diganti)  *🤸*

In [ ]:
cluster = 2
x = np.array([1, 2, 4, 5])
y = np.array([1, 1, 3, 4])
px = np.array([1, 2])
py = np.array([1, 1])
itr = 0

## Tempat untuk komputasi-1 ⛏

In [ ]:
cluster = 2
itr = 0
x = np.array([0.40, 0.22, 0.35, 0.26, 0.08, 0.45])
y = np.array([0.53, 0.38, 0.32, 0.19, 0.41, 0.30])
px = np.array([0.4, 0.2])
py = np.array([0.3, 0.3])

In [ ]:
kmeans(cluster, x, y, px, py, itr)

iterasi ke- 0
x =  [0.4  0.22 0.35 0.26 0.08 0.45]
y =  [0.53 0.38 0.32 0.19 0.41 0.3 ]
P ke- 1 :  [0.4 0.3]
P ke- 2 :  [0.2 0.3]


Hasil distance: 
[[0.23       0.19697716 0.05385165 0.17804494 0.33837849 0.05      ]
 [0.30479501 0.08246211 0.15132746 0.12529964 0.16278821 0.25      ]]


Hasil clustering: 
[[1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 1. 0.]]


nsum cluster ke- 0 :  3.0
xsum cluster ke- 0 :  1.2
ysum cluster ke- 0 :  1.1500000000000001


nsum cluster ke- 1 :  3.0
xsum cluster ke- 1 :  0.5599999999999999
ysum cluster ke- 1 :  0.98


pnew:
P new ke- 1 :  [0.4        0.38333333]
P new ke- 2 :  [0.18666667 0.32666667]


iterasi ke- 1
x =  [0.4  0.22 0.35 0.26 0.08 0.45]
y =  [0.53 0.38 0.32 0.19 0.41 0.3 ]
P ke- 1 :  [0.4        0.38333333]
P ke- 2 :  [0.18666667 0.32666667]


Hasil distance: 
[[0.14666667 0.18003086 0.08069146 0.23870018 0.32110919 0.09718253]
 [0.29471267 0.06289321 0.16346933 0.15509853 0.1353596  0.2646801 ]]


Hasil clustering: 
[[1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 

## Tempat untuk komputasi-2 ⛏

In [ ]:
cluster = 3
itr = 0
x = np.array([0.40, 0.22, 0.35, 0.26, 0.08, 0.45])
y = np.array([0.53, 0.38, 0.32, 0.19, 0.41, 0.30])
px = np.array([0.4, 0.2, 0.3])
py = np.array([0.3, 0.3, 0.1])

In [ ]:
kmeans(cluster, x, y, px, py, itr)

iterasi ke- 0
x =  [0.4  0.22 0.35 0.26 0.08 0.45]
y =  [0.53 0.38 0.32 0.19 0.41 0.3 ]
P ke- 1 :  [0.4 0.3]
P ke- 2 :  [0.2 0.3]
P ke- 3 :  [0.3 0.1]


Hasil distance: 
[[0.23       0.19697716 0.05385165 0.17804494 0.33837849 0.05      ]
 [0.30479501 0.08246211 0.15132746 0.12529964 0.16278821 0.25      ]
 [0.4414748  0.2912044  0.22561028 0.09848858 0.38013156 0.25      ]]


Hasil clustering: 
[[1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]]


nsum cluster ke- 0 :  3.0
xsum cluster ke- 0 :  1.2
ysum cluster ke- 0 :  1.1500000000000001


nsum cluster ke- 1 :  2.0
xsum cluster ke- 1 :  0.3
ysum cluster ke- 1 :  0.79


nsum cluster ke- 2 :  1.0
xsum cluster ke- 2 :  0.26
ysum cluster ke- 2 :  0.19


pnew:
P new ke- 1 :  [0.4        0.38333333]
P new ke- 2 :  [0.15  0.395]
P new ke- 3 :  [0.26 0.19]


iterasi ke- 1
x =  [0.4  0.22 0.35 0.26 0.08 0.45]
y =  [0.53 0.38 0.32 0.19 0.41 0.3 ]
P ke- 1 :  [0.4        0.38333333]
P ke- 2 :  [0.15  0.395]
P ke- 3 :  [0.26 0.19]


H

## STOP ❗❗❗❗❗❗❗❗ 

## Bawah hanya coretan 📓

### K-Means Khusus 2 Cluster 

In [ ]:
def kmeans2(x, y, p1, p2, itr):
  n = len(x)
  d = np.zeros([2, n])
  g = np.zeros([2, n])
  nsum = np.zeros(2)
  xsum = np.zeros(2)
  ysum = np.zeros(2)

  for i in range(0, n):
    titik = np.array([x[i], y[i]])
    d[0][i] = euclidean(titik, p1)
    d[1][i] = euclidean(titik, p2)
    if d[0][i] < d[1][i]:
      g[0][i] = 1
    else:
      g[1][i] = 1

  for i in range(0, n):
    if g[0][i] == 1:
      nsum[0] = nsum[0] + 1
      xsum[0] = xsum[0] + x[i]
      ysum[0] = ysum[0] + y[i]
    else:
      nsum[1] = nsum[1] + 1
      xsum[1] = xsum[1] + x[i]
      ysum[1] = ysum[1] + y[i]

  p1new = np.array([xsum[0]/nsum[0], ysum[0]/nsum[0]])
  p2new = np.array([xsum[1]/nsum[1], ysum[1]/nsum[1]])

  print("iterasi ke-", itr)
  print("p1 =  ", p1)
  print("p2 =  ", p2)
  print("\n")
  
  print("Hasil distance: ")
  print(d)
  print("\n")

  print("Hasil clustering: ")
  print(g)
  print("\n")

  print("nsum cluster 1 =  ", nsum[0])
  print("xsum cluster 1 =  ", xsum[0])
  print("ysum cluster 1 =  ", ysum[0])
  print("\n")

  print("nsum cluster 2 =  ", nsum[1])
  print("xsum cluster 2 =  ", xsum[1])
  print("ysum cluster 2 =  ", ysum[1])
  print("\n")

  print("p1 new =  ", p1new)
  print("p2 new =  ", p2new)
  print("\n==============================================================\n")

  if((p1 != p1new).all() or (p2 != p2new).all()):
    itr = itr + 1
    kmeans2(x, y, p1new, p2new, itr)



In [ ]:
cluster = 2
x = np.array([1, 2, 4, 5])
y = np.array([1, 1, 3, 4])
p1 = np.array([1, 1])
p2 = np.array([2, 1])
itr = 0

In [ ]:
kmeans2(x, y, p1, p2, itr)

iterasi ke- 0
p1 =   [1 1]
p2 =   [2 1]


Hasil distance: 
[[0.         1.         3.60555128 5.        ]
 [1.         0.         2.82842712 4.24264069]]


Hasil clustering: 
[[1. 0. 0. 0.]
 [0. 1. 1. 1.]]


nsum cluster 1 =   1.0
xsum cluster 1 =   1.0
ysum cluster 1 =   1.0


nsum cluster 2 =   3.0
xsum cluster 2 =   11.0
ysum cluster 2 =   8.0


p1 new =   [1. 1.]
p2 new =   [3.66666667 2.66666667]


iterasi ke- 1
p1 =   [1. 1.]
p2 =   [3.66666667 2.66666667]


Hasil distance: 
[[0.         1.         3.60555128 5.        ]
 [3.14466038 2.3570226  0.47140452 1.88561808]]


Hasil clustering: 
[[1. 1. 0. 0.]
 [0. 0. 1. 1.]]


nsum cluster 1 =   2.0
xsum cluster 1 =   3.0
ysum cluster 1 =   2.0


nsum cluster 2 =   2.0
xsum cluster 2 =   9.0
ysum cluster 2 =   7.0


p1 new =   [1.5 1. ]
p2 new =   [4.5 3.5]


iterasi ke- 2
p1 =   [1.5 1. ]
p2 =   [4.5 3.5]


Hasil distance: 
[[0.5        0.5        3.20156212 4.60977223]
 [4.30116263 3.53553391 0.70710678 0.70710678]]


Hasil clusterin