## IMPORT LIBRARY 📚

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import distance

## Hitung Jarak Titik Euclidean 📏

In [ ]:
def euclidean(x, p):
  return distance.euclidean(x, p)

## K-Means Algorithm For K Cluster ⚡

In [ ]:
def kmeans(cluster, x, y, px, py, itr):
  n = len(x)
  d = np.zeros([cluster, n])
  g = np.zeros([cluster, n])
  nsum = np.zeros(cluster)
  xsum = np.zeros(cluster)
  ysum = np.zeros(cluster)
  compareMin = np.zeros(cluster)
  pxnew = np.zeros(cluster)
  pynew = np.zeros(cluster)

  for i in range(0, n):
    # Mencari jarak titik dengan centroid
    xy = np.array([x[i], y[i]])
    for j in range(0, cluster):
      cent = np.array([px[j], py[j]])
      d[j][i] = euclidean(xy, cent)
      compareMin[j] = d[j][i]
    # Clustering berdasarkan nilai paling dekat dengan 0
    idxMin = 0
    minValue = compareMin[0]
    for k in range(0, cluster):
      if ( minValue > compareMin[k] ):
        idxMin = k
        minValue = compareMin[k]
    g[idxMin][i] = 1

  # Membuat nilai centroid baru
  for i in range(0, cluster):
    for j in range(0, n):
      if (g[i][j] == 1):
        nsum[i] = nsum[i] + 1
        xsum[i] = xsum[i] + x[j]
        ysum[i] = ysum[i] + y[j]
  for i in range(0, cluster):
    xmean = xsum[i]/nsum[i]
    ymean = ysum[i]/nsum[i]
    pxnew[i] = xmean
    pynew[i] = ymean

  # Print Detail Komputasi
  print("iterasi ke-", itr)
  print('x = ', x)
  print('y = ', y)
  for i in range(0, cluster):
    cent = np.array([px[i], py[i]])
    print("P ke-", i+1, ': ', cent)
  print("\n")
  
  print("Hasil distance: ")
  print(d)
  print("\n")

  print("Hasil clustering: ")
  print(g)
  print("\n")

  for i in range(0, cluster):
    print("nsum cluster ke-", i, ': ', nsum[i])
    print("xsum cluster ke-", i, ': ', xsum[i])
    print("ysum cluster ke-", i, ': ', ysum[i])
    print('\n')

  print('pnew:')
  for i in range(0, cluster):
    cent = np.array([pxnew[i], pynew[i]])
    print("P new ke-", i+1, ': ', cent)
  print("\n==============================================================\n")

  # Cek centroid awal dan centroid baru apakah sama
  loop = 0
  valid = True
  while(valid and loop < cluster):
    if((px[loop] != pxnew[loop]) or (py[loop] != pynew[loop])):
      valid = False
    loop = loop + 1
  
  # Jika nilai centroid baru dan lama berbeda maka lakukan rekursif
  if(valid == False):
    itr = itr + 1
    kmeans(cluster, x, y, pxnew, pynew, itr)



## Contoh Eksekusi 2 Cluster ⛏

In [ ]:
cluster = 2
itr = 0
x = np.array([0.40, 0.22, 0.35, 0.26, 0.08, 0.45])
y = np.array([0.53, 0.38, 0.32, 0.19, 0.41, 0.30])
px = np.array([0.4, 0.2])
py = np.array([0.3, 0.3])

In [ ]:
kmeans(cluster, x, y, px, py, itr)

iterasi ke- 0
x =  [0.4  0.22 0.35 0.26 0.08 0.45]
y =  [0.53 0.38 0.32 0.19 0.41 0.3 ]
P ke- 1 :  [0.4 0.3]
P ke- 2 :  [0.2 0.3]


Hasil distance: 
[[0.23       0.19697716 0.05385165 0.17804494 0.33837849 0.05      ]
 [0.30479501 0.08246211 0.15132746 0.12529964 0.16278821 0.25      ]]


Hasil clustering: 
[[1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 1. 0.]]


nsum cluster ke- 0 :  3.0
xsum cluster ke- 0 :  1.2
ysum cluster ke- 0 :  1.1500000000000001


nsum cluster ke- 1 :  3.0
xsum cluster ke- 1 :  0.5599999999999999
ysum cluster ke- 1 :  0.98


pnew:
P new ke- 1 :  [0.4        0.38333333]
P new ke- 2 :  [0.18666667 0.32666667]


iterasi ke- 1
x =  [0.4  0.22 0.35 0.26 0.08 0.45]
y =  [0.53 0.38 0.32 0.19 0.41 0.3 ]
P ke- 1 :  [0.4        0.38333333]
P ke- 2 :  [0.18666667 0.32666667]


Hasil distance: 
[[0.14666667 0.18003086 0.08069146 0.23870018 0.32110919 0.09718253]
 [0.29471267 0.06289321 0.16346933 0.15509853 0.1353596  0.2646801 ]]


Hasil clustering: 
[[1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 

## Contoh Eksekusi 3 Cluster ⛏

In [ ]:
cluster = 3
itr = 0
x = np.array([0.40, 0.22, 0.35, 0.26, 0.08, 0.45])
y = np.array([0.53, 0.38, 0.32, 0.19, 0.41, 0.30])
px = np.array([0.4, 0.2, 0.3])
py = np.array([0.3, 0.3, 0.1])

In [ ]:
kmeans(cluster, x, y, px, py, itr)

iterasi ke- 0
x =  [0.4  0.22 0.35 0.26 0.08 0.45]
y =  [0.53 0.38 0.32 0.19 0.41 0.3 ]
P ke- 1 :  [0.4 0.3]
P ke- 2 :  [0.2 0.3]
P ke- 3 :  [0.3 0.1]


Hasil distance: 
[[0.23       0.19697716 0.05385165 0.17804494 0.33837849 0.05      ]
 [0.30479501 0.08246211 0.15132746 0.12529964 0.16278821 0.25      ]
 [0.4414748  0.2912044  0.22561028 0.09848858 0.38013156 0.25      ]]


Hasil clustering: 
[[1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]]


nsum cluster ke- 0 :  3.0
xsum cluster ke- 0 :  1.2
ysum cluster ke- 0 :  1.1500000000000001


nsum cluster ke- 1 :  2.0
xsum cluster ke- 1 :  0.3
ysum cluster ke- 1 :  0.79


nsum cluster ke- 2 :  1.0
xsum cluster ke- 2 :  0.26
ysum cluster ke- 2 :  0.19


pnew:
P new ke- 1 :  [0.4        0.38333333]
P new ke- 2 :  [0.15  0.395]
P new ke- 3 :  [0.26 0.19]


iterasi ke- 1
x =  [0.4  0.22 0.35 0.26 0.08 0.45]
y =  [0.53 0.38 0.32 0.19 0.41 0.3 ]
P ke- 1 :  [0.4        0.38333333]
P ke- 2 :  [0.15  0.395]
P ke- 3 :  [0.26 0.19]


H